import os
import sys
import rtconfig

if os.getenv('RTT_ROOT'):
    RTT_ROOT = os.getenv('RTT_ROOT')
else:
    RTT_ROOT = os.path.normpath(os.getcwd() + '/../..')

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
from building import *

TARGET = 'rtthread-beaglebone.' + rtconfig.TARGET_EXT

#SetOption('experimental','ninja')
DefaultEnvironment(tools=[])
env = Environment(tools = ['mingw', 'textfile'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CFLAGS = rtconfig.CFLAGS,
    CXX= rtconfig.CXX, CXXFLAGS = rtconfig.CFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)
env.Tool('ninja')

Export('RTT_ROOT')
Export('rtconfig')

def ExpandList(l, expandList = []):
    for x in l:
        if type(x) != list:
            expandList.append(x)
        else:
            ExpandList(x)
    return expandList

# prepare building environment
objs = ExpandList(PrepareBuilding(env, RTT_ROOT))

cppPathStr = "-I" + "\n-I".join(env["CPPPATH"]).replace("\\", "/")
compileIncPath = os.path.normpath(os.path.join(rtconfig.EXEC_PATH, "..", "include"))
incPathsFile = env.Textfile("build/__cpp_path.txt", [
    "-I%s\n" % (os.path.join(compileIncPath, "libcxx").replace("\\", "/")),
    "-I%s\n" % (compileIncPath.replace("\\", "/")),
    cppPathStr
])

def _add_scanner(builder):
    def new_scanner(node, env, path):
        return incPathsFile
       
    builder.builder.target_scanner = SCons.Scanner.Scanner(
        function=new_scanner,
        path_function=SCons.Script.FindPathDirs('CPPPATH'),
    )
for object_builder in SCons.Tool.createObjBuilders(env):
    _add_scanner(object_builder)

env["_CPPINCFLAGS"] = "@%s" % (incPathsFile[0].path)

# make a building
DoBuilding(TARGET, objs)
