# for module compiling
import os
import SCons
from building import *

Import('RTT_ROOT')

cwd = str(Dir('#'))
objs = []

for item in os.listdir(cwd):
    path = os.path.join(cwd, item)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')